version: '3'

services:
  postgres:
    container_name: bank-postgres
    image: 'postgres:16-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankapi
      PGTZ: "Asia/Tokyo"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/