version: "3"

services:
  api:
    image: startup2023/bank-api
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    env_file:
      - .env
    environment:
      - DB_SOURCE=${DB_SOURCE}
      - DB_SOURCE_TEST=${DB_SOURCE_TEST}
    depends_on:
      - postgres

  postgres:
    container_name: bank-postgres
    image: 'postgres:16.3-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankapi
      PGTZ: "Asia/Tokyo"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5