version: "3"

services:
  caddy:
    image: startup2023/bank-caddy-production:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  api-service:
    image: startup2023/bank-api
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: bank-postgres
    image: 'postgres:16.3-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankapi
      PGTZ: "Asia/Tokyo"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  caddy_data:
    external: true
  caddy_config: