version: '3.7'

services:
  postgres:
    image: 'postgres:16.3-alpine'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankapi
      PGTZ: "Asia/Tokyo"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bankapp_network

  api-service:
    image: startup2023/bank-api:latest
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DB_SOURCE_PROD=${DB_SOURCE_PROD}
      - DB_SOURCE_TEST=${DB_SOURCE_TEST}
    depends_on:
      - postgres
    networks:
      - bankapp_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-service
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - bankapp_network

networks:
  bankapp_network:
    driver: overlay
