// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: referral.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createReferralCode = `-- name: CreateReferralCode :one
INSERT INTO referral_codes (referral_code, referrer_account_id, created_at)
VALUES ($1, $2, $3)
RETURNING id, referral_code, referrer_account_id, is_used, created_at, used_at
`

type CreateReferralCodeParams struct {
	ReferralCode      string    `json:"referral_code"`
	ReferrerAccountID int64     `json:"referrer_account_id"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) CreateReferralCode(ctx context.Context, arg CreateReferralCodeParams) (ReferralCode, error) {
	row := q.queryRow(ctx, q.createReferralCodeStmt, createReferralCode, arg.ReferralCode, arg.ReferrerAccountID, arg.CreatedAt)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.ReferralCode,
		&i.ReferrerAccountID,
		&i.IsUsed,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const createReferralHistory = `-- name: CreateReferralHistory :one
INSERT INTO referral_history (referrer_account_id, referred_account_id, referral_code_id, referral_date, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, referrer_account_id, referred_account_id, referral_code_id, referral_date, created_at
`

type CreateReferralHistoryParams struct {
	ReferrerAccountID int64     `json:"referrer_account_id"`
	ReferredAccountID int64     `json:"referred_account_id"`
	ReferralCodeID    int64     `json:"referral_code_id"`
	ReferralDate      time.Time `json:"referral_date"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) CreateReferralHistory(ctx context.Context, arg CreateReferralHistoryParams) (ReferralHistory, error) {
	row := q.queryRow(ctx, q.createReferralHistoryStmt, createReferralHistory,
		arg.ReferrerAccountID,
		arg.ReferredAccountID,
		arg.ReferralCodeID,
		arg.ReferralDate,
		arg.CreatedAt,
	)
	var i ReferralHistory
	err := row.Scan(
		&i.ID,
		&i.ReferrerAccountID,
		&i.ReferredAccountID,
		&i.ReferralCodeID,
		&i.ReferralDate,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralCode = `-- name: GetReferralCode :one
SELECT id, referral_code, referrer_account_id, is_used, created_at, used_at FROM referral_codes
WHERE referral_code = $1
LIMIT 1
`

func (q *Queries) GetReferralCode(ctx context.Context, referralCode string) (ReferralCode, error) {
	row := q.queryRow(ctx, q.getReferralCodeStmt, getReferralCode, referralCode)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.ReferralCode,
		&i.ReferrerAccountID,
		&i.IsUsed,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const getReferralHistory = `-- name: GetReferralHistory :many
SELECT id, referrer_account_id, referred_account_id, referral_code_id, referral_date, created_at FROM referral_history
WHERE referrer_account_id = $1
ORDER BY referral_date
`

func (q *Queries) GetReferralHistory(ctx context.Context, referrerAccountID int64) ([]ReferralHistory, error) {
	rows, err := q.query(ctx, q.getReferralHistoryStmt, getReferralHistory, referrerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReferralHistory{}
	for rows.Next() {
		var i ReferralHistory
		if err := rows.Scan(
			&i.ID,
			&i.ReferrerAccountID,
			&i.ReferredAccountID,
			&i.ReferralCodeID,
			&i.ReferralDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReferralHistoryByDate = `-- name: GetReferralHistoryByDate :many
SELECT id, referrer_account_id, referred_account_id, referral_code_id, referral_date, created_at FROM referral_history
WHERE referrer_account_id = $1
  AND referral_date >= $2 AND referral_date <= $3
ORDER BY referral_date
`

type GetReferralHistoryByDateParams struct {
	ReferrerAccountID int64     `json:"referrer_account_id"`
	ReferralDate      time.Time `json:"referral_date"`
	ReferralDate_2    time.Time `json:"referral_date_2"`
}

func (q *Queries) GetReferralHistoryByDate(ctx context.Context, arg GetReferralHistoryByDateParams) ([]ReferralHistory, error) {
	rows, err := q.query(ctx, q.getReferralHistoryByDateStmt, getReferralHistoryByDate, arg.ReferrerAccountID, arg.ReferralDate, arg.ReferralDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReferralHistory{}
	for rows.Next() {
		var i ReferralHistory
		if err := rows.Scan(
			&i.ID,
			&i.ReferrerAccountID,
			&i.ReferredAccountID,
			&i.ReferralCodeID,
			&i.ReferralDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReferralsByDateRange = `-- name: GetReferralsByDateRange :one
SELECT COUNT(*) FROM referral_codes
    WHERE referrer_account_id = $1
    AND is_used = true
    AND created_at >= $2 AND created_at <= $3
`

type GetReferralsByDateRangeParams struct {
	ReferrerAccountID int64     `json:"referrer_account_id"`
	CreatedAt         time.Time `json:"created_at"`
	CreatedAt_2       time.Time `json:"created_at_2"`
}

func (q *Queries) GetReferralsByDateRange(ctx context.Context, arg GetReferralsByDateRangeParams) (int64, error) {
	row := q.queryRow(ctx, q.getReferralsByDateRangeStmt, getReferralsByDateRange, arg.ReferrerAccountID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnusedReferralCodes = `-- name: GetUnusedReferralCodes :many
SELECT id, referral_code, referrer_account_id, is_used, created_at, used_at FROM referral_codes
WHERE is_used = true
  AND referrer_account_id = $1
  AND created_at >= $2 AND created_at <= $3
`

type GetUnusedReferralCodesParams struct {
	ReferrerAccountID int64     `json:"referrer_account_id"`
	CreatedAt         time.Time `json:"created_at"`
	CreatedAt_2       time.Time `json:"created_at_2"`
}

func (q *Queries) GetUnusedReferralCodes(ctx context.Context, arg GetUnusedReferralCodesParams) ([]ReferralCode, error) {
	rows, err := q.query(ctx, q.getUnusedReferralCodesStmt, getUnusedReferralCodes, arg.ReferrerAccountID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReferralCode{}
	for rows.Next() {
		var i ReferralCode
		if err := rows.Scan(
			&i.ID,
			&i.ReferralCode,
			&i.ReferrerAccountID,
			&i.IsUsed,
			&i.CreatedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReferralCodeUsed = `-- name: MarkReferralCodeUsed :one
UPDATE referral_codes
SET is_used = true, used_at = $2
WHERE referral_code = $1
RETURNING id, referral_code, referrer_account_id, is_used, created_at, used_at
`

type MarkReferralCodeUsedParams struct {
	ReferralCode string       `json:"referral_code"`
	UsedAt       sql.NullTime `json:"used_at"`
}

func (q *Queries) MarkReferralCodeUsed(ctx context.Context, arg MarkReferralCodeUsedParams) (ReferralCode, error) {
	row := q.queryRow(ctx, q.markReferralCodeUsedStmt, markReferralCodeUsed, arg.ReferralCode, arg.UsedAt)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.ReferralCode,
		&i.ReferrerAccountID,
		&i.IsUsed,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}
