name: ci-test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bankapi
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
        id: go

      - name: Install Goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -p 5432 -U postgres && break
            echo "PostgreSQL is not ready yet..."
            sleep 2
          done
          pg_isready -h 127.0.0.1 -p 5432 -U postgres

      - name: Set Environment Variables
        run: |
          echo "DB_SOURCE=${{ secrets.DB_SOURCE }}" >> $GITHUB_ENV
          echo "DB_SOURCE_TEST=${{ secrets.DB_SOURCE_TEST }}" >> $GITHUB_ENV
          echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> $GITHUB_ENV

      - name: Create Test Database
        run: make createdb

      - name: Run Migrations
        run: make dbmigrate-test

      - name: Tidy Go Modules
        run: go mod tidy

      - name: Test Store
        run: go test -tags=storetest -v ./db/sqlc

      - name: Test Handler
        run: go test -tags=handlertest -v ./api

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

#      - name: Build Docker image
#        run: |
#          docker build -t bankapi:latest .

#      - name: Tag docker image
#        run: |
#          REPOSITORY_URI="${{ secrets.ECR_REPOSITORY_URI }}"
#          IMAGE_TAG="${GITHUB_SHA}"
#          docker tag bankapi:latest $REPOSITORY_URI:$IMAGE_TAG
#
#      - name: Push to Amazon ECR
#        run: |
#          REPOSITORY_URI="${{ secrets.ECR_REPOSITORY_URI }}"
#          IMAGE_TAG="${GITHUB_SHA}"
#          docker push $REPOSITORY_URI:$IMAGE_TAG

      - name: Build, tag, and push image to amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: bankapi
          IMAGE_TAG: ${{GITHUB_SHA}}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
